blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://teams.microsoft.com/l/channel/19%3a8b5d2a982c414973af5cc4a73cf63c0d%40thread.skype/Git?groupId=fcefae7a-db06-4f6d-b7e9-a479f20476c3&tenantId=a866874a-d0e3-4a03-a79d-4c893ab51296
    about: Please ask and answer questions here.